name: tests

on:
  push:
    branches: ["main"]

  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            os: ubuntu-22.04

          - ruby: "4.0"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache bundler
        uses: actions/cache@v4
        with:
          path: .bundle
          key: ${{ runner.os }}-bundler-${{ matrix.ruby }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-${{ matrix.ruby }}-

      - name: Install gems
        run: nix develop . --command bundle install

      - name: Cache models
        uses: actions/cache@v4
        with:
          path: tmp/models
          key: ${{ runner.os }}-models-${{ matrix.ruby }}-variants
          restore-keys: |
            ${{ runner.os }}-models-${{ matrix.ruby }}

      - name: Run unit tests
        run: nix develop . --command bash -lc "bundle exec rspec"

      - name: Run integration tests
        run: nix develop . --command bash -lc "bundle exec rake spec:integration"
